config_version = 1
device="cpu"

agent_name="InSampleAC"
env_name="Hopper"
dataset="expert"
evaluation_criteria="return"

discrete_control=false
state_dim=11
action_dim=3

max_steps=1_000_000
log_interval=10_000
timeout=1000

hidden_units=256
batch_size=256

polyak=0.995

gamma=0.99

use_target_network=1
target_network_update_freq=1

learning_rate=1e-3
tau=0.01


#new protocol
[sweep]
run=[0, 1, 2, 3, 4]