config_version = 1
device="cpu"

agent_name="TsallisKLInAC"
env_name="HalfCheetah"
dataset="medexp"
evaluation_criteria="return"

discrete_control=false
state_dim=17
action_dim=6

max_steps=1_000_000
log_interval=10_000
timeout=1000

hidden_units=256
batch_size=256

polyak=0.995

gamma=0.99
q=2

use_target_network=1
target_network_update_freq=1

[sweep]
learning_rate=[1.52587890625e-5, 6.103515625e-5, 0.000244140625, 0.0009765625, 0.001953125,  0.0078125]
tau=[0.0001, 0.001, 0.01, 0.1]
alpha=[0.1, 0.5, 0.9]
run=[0, 1, 2, 3]