config_version = 1
device="cpu"
# info="0"

agent_name="TsallisInAC"
env_name="Ant"
dataset="medexp"
evaluation_criteria="return"

discrete_control=false
state_dim=111
action_dim=8

max_steps=2_000
log_interval=100
timeout=100

hidden_units=256
batch_size=256

tau=0.01
polyak=0.995
learning_rate=3e-4
gamma=0.99

use_target_network=1
target_network_update_freq=1

[sweep]
run=[0, 1, 2, 3, 4, 5]