at = [
    {"label": "IQL_medium",
     "control_sweep": "data/output/test_v9_batch256/ant/iql_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medium/sweep", [1]],#[3]],
     # "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/iql_online/data_medium/best", [0]],
     },
    {"label": "IQL_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/iql_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/ant/iql_offline/data_expert/sweep", [3]],
     # "control": ["data/output/test_v9_batch256/ant/iql_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/iql_online/data_expert/best", [0]],
     },
    {"label": "IQL_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/ant/iql_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medrep/sweep", [3]],#[1]],
     # "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/iql_online/data_medrep/best", [0]],
     },
    {"label": "IQL_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/iql_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medexp/sweep", [3]],
     # "control": ["data/output/test_v9_batch256/ant/iql_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/iql_online/data_medexp/best", [0]],
     },
    {"label": "AWAC_medium",
     "control_sweep": "data/output/test_v9_batch256/ant/awac_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medium/sweep", [0]],#[2]],
     # "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/awac_online/data_medium/best", [0]],
     },
    {"label": "AWAC_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/awac_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/ant/awac_offline/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/awac_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/awac_online/data_expert/best", [0]],
     },
    {"label": "AWAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/ant/awac_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medrep/sweep", [4]],#[2]],
     # "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/awac_online/data_medrep/best", [0]],
     },
    {"label": "AWAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/awac_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/awac_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/awac_online/data_medexp/best", [0]],
     },
    {"label": "InSampleAC_medium",
     "control_sweep": "data/output/test_v9_batch256/ant/in_sample_ac/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medium/sweep", [1]],# [3]],
     # "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/in_sample_ac_online/data_medium/best", [0]],
     },
    {"label": "InSampleAC_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/in_sample_ac/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_expert/sweep", [4]],
     # "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/in_sample_ac_online/data_expert/best", [0]],
     },
    {"label": "InSampleAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/ant/in_sample_ac/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medrep/sweep", [1]],# [3]],
     # "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/in_sample_ac_online/data_medrep/best", [0]],
     },
    {"label": "InSampleAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/in_sample_ac/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medexp/sweep", [4]],
     # "control": ["data/output/test_v9_batch256/ant/in_sample_ac/data_medexp/best", [0]], #[2]],
     "fine_tune": ["data/output/test_v9_batch256/ant/in_sample_ac_online/data_medexp/best", [0]],
     },
    {"label": "TD3BC_medium",
     "control_sweep": "data/output/test_v9_batch256/ant/td3_bc/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medium/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/td3_bc_online/data_medium/best2", [0]],
     },
    {"label": "TD3BC_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/td3_bc/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/ant/td3_bc/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/td3_bc/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/td3_bc_online/data_expert/best2", [0]],
     },
    {"label": "TD3BC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/ant/td3_bc/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/td3_bc_online/data_medrep/best", [0]],
     },
    {"label": "TD3BC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/td3_bc/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/ant/td3_bc/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/td3_bc_online/data_medexp/best2", [0]],
     },
    {"label": "CQL_medium",
     "control_sweep": "data/output/test_v9_batch256/ant/cqlsac_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/ant/cqlsac_offline/data_medium/sweep", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/cqlsac_online/data_medium/best", [0]],
     },
    {"label": "CQL_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/cqlsac_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/ant/cqlsac_offline/data_expert/sweep", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/cqlsac_online/data_expert/best", [0]],
     },
    {"label": "CQL_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/ant/cqlsac_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/ant/cqlsac_offline/data_medrep/sweep", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/cqlsac_online/data_medrep/best", [0]],
     },
    {"label": "CQL_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/ant/cqlsac_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/ant/cqlsac_offline/data_medexp/sweep", [0]],
     "fine_tune": ["data/output/test_v9_batch256/ant/cqlsac_online/data_medexp/best", [0]],
     }
]

hc = [
    {"label": "IQL_medium",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/iql_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medium/sweep", [2]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/iql_online/data_medium/best", [0]],
     },
    {"label": "IQL_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/iql_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_expert/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/iql_online/data_expert/best", [0]],
     },
    {"label": "IQL_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/iql_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medrep/sweep", [2]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/iql_online/data_medrep/best", [0]],
     },
    {"label": "IQL_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/iql_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medexp/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/iql_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/iql_online/data_medexp/best", [0]],
     },
    {"label": "AWAC_medium",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/awac_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medium/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/awac_online/data_medium/best2", [0]],
     },
    {"label": "AWAC_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/awac_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/awac_online/data_expert/best2", [0]],
     },
    {"label": "AWAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/awac_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/awac_online/data_medrep/best", [0]],
     },
    {"label": "AWAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/awac_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/awac_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/awac_online/data_medexp/best", [0]],
     },
    {"label": "InSampleAC_medium",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medium/sweep", [3]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac_online/data_medium/best", [0]],
     },
    {"label": "InSampleAC_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_expert/sweep", [4]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac_online/data_expert/best", [0]],
     },
    {"label": "InSampleAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medrep/sweep", [6]],#[1]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac_online/data_medrep/best", [0]],
     },
    {"label": "InSampleAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medexp/sweep", [9]],# [2]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/in_sample_ac_online/data_medexp/best", [0]],
     },
    {"label": "TD3BC_medium",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/td3_bc/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medium/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/td3_bc_online/data_medium/best2", [0]],
     },
    {"label": "TD3BC_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/td3_bc/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/td3_bc_online/data_expert/best", [0]],
     },
    {"label": "TD3BC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/td3_bc/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/td3_bc_online/data_medrep/best", [0]],
     },
    {"label": "TD3BC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/halfcheetah/td3_bc/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/halfcheetah/td3_bc/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/halfcheetah/td3_bc_online/data_medexp/best", [0]],
     },
]

hp = [
    {"label": "IQL_medium",
     "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medium/sweep", [3]],
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/iql_online/data_medium/best", [0]],
     },
    {"label": "IQL_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_expert/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/iql_online/data_expert/best", [0]],
     },
    {"label": "IQL_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medrep/sweep", [3]],
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medrep/best", [0]],
     # "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_medrep/sweep2",
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medrep/sweep2", [1]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/iql_online/data_medrep/best", [0]],
     },
    {"label": "IQL_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medexp/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medexp/best", [0]],
     # "control_sweep": "data/output/test_v9_batch256/hopper/iql_offline/data_medexp/sweep2",
     # "control": ["data/output/test_v9_batch256/hopper/iql_offline/data_medexp/sweep2", [1]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/iql_online/data_medexp/best", [0]],
     },
    {"label": "AWAC_medium",
     "control_sweep": "data/output/test_v9_batch256/hopper/awac_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medium/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/awac_online/data_medium/best", [0]],
     },
    {"label": "AWAC_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/awac_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/awac_online/data_expert/best2", [0]],
     },
    {"label": "AWAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/hopper/awac_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medrep/sweep", [3]],#[1]],
     # "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/awac_online/data_medrep/best", [0]],
     },
    {"label": "AWAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/awac_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/awac_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/awac_online/data_medexp/best2", [0]],
     },
    {"label": "InSampleAC_medium",
     "control_sweep": "data/output/test_v9_batch256/hopper/in_sample_ac/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medium/sweep", [2]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/in_sample_ac_online/data_medium/best", [0]],
     },
    {"label": "InSampleAC_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/in_sample_ac/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_expert/sweep", [9]],# [4]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/in_sample_ac_online/data_expert/best", [0]],
     },
    {"label": "InSampleAC_medium_replay",
     # "control_sweep": "data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep_longer",
     "control_sweep": "data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep_longer", [3]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep_longer_nostablize", [3]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep_nostablize_batch100", [3]],
     # "control": ["data/output/test_v9_batch256/hopper/in_sample_ac/data_medrep/sweep_stablized_batch100", [3]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/in_sample_ac_online/data_medrep/best", [0]],
     },
    {"label": "TD3BC_medium",
     "control_sweep": "data/output/test_v9_batch256/hopper/td3_bc/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medium/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/td3_bc_online/data_medium/best2", [0]],
     },
    {"label": "TD3BC_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/td3_bc/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/td3_bc_online/data_expert/best2", [0]],
     },
    {"label": "TD3BC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/hopper/td3_bc/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/td3_bc_online/data_medrep/best2", [0]],
     },
    {"label": "TD3BC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/hopper/td3_bc/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/hopper/td3_bc/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/hopper/td3_bc_online/data_medexp/best2", [0]],
     },
]

wk2d = [
    {"label": "IQL_medium",
     "control_sweep": "data/output/test_v9_batch256/walker2d/iql_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medium/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/iql_online/data_medium/best", [0]],
     },
    {"label": "IQL_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/iql_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_expert/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/iql_online/data_expert/best", [0]],
     },
    {"label": "IQL_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/walker2d/iql_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medrep/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/iql_online/data_medrep/best", [0]],
     },
    {"label": "IQL_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/iql_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medexp/sweep", [1]],
     # "control": ["data/output/test_v9_batch256/walker2d/iql_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/iql_online/data_medexp/best", [0]],
     },
    {"label": "AWAC_medium",
     "control_sweep": "data/output/test_v9_batch256/walker2d/awac_offline/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medium/sweep", [3]],#[2]],
     # "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/awac_online/data_medium/best", [0]],
     },
    {"label": "AWAC_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/awac_offline/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/awac_online/data_expert/best", [0]],
     },
    {"label": "AWAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/walker2d/awac_offline/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/awac_online/data_medrep/best", [0]],
     },
    {"label": "AWAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/awac_offline/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medexp/sweep", [2]],
     # "control": ["data/output/test_v9_batch256/walker2d/awac_offline/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/awac_online/data_medexp/best", [0]],
     },
    {"label": "InSampleAC_medium",
     "control_sweep": "data/output/test_v9_batch256/walker2d/in_sample_ac/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medium/sweep", [8]],# [3]],
     # "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/in_sample_ac_online/data_medium/best", [0]],
     },
    {"label": "InSampleAC_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/in_sample_ac/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_expert/sweep", [7]],# [4]],
     # "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/in_sample_ac_online/data_expert/best", [0]],
     },
    {"label": "InSampleAC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/walker2d/in_sample_ac/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medrep/sweep", [1]],#[3]],
     # "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/in_sample_ac_online/data_medrep/best", [0]],
     },
    {"label": "InSampleAC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/in_sample_ac/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medexp/sweep", [2]],
     # "control": ["data/output/test_v9_batch256/walker2d/in_sample_ac/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/in_sample_ac_online/data_medexp/best", [0]],
     },
    {"label": "TD3BC_medium",
     "control_sweep": "data/output/test_v9_batch256/walker2d/td3_bc/data_medium/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medium/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medium/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/td3_bc_online/data_medium/best2", [0]],
     },
    {"label": "TD3BC_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/td3_bc/data_expert/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_expert/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_expert/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/td3_bc_online/data_expert/best2", [0]],
     },
    {"label": "TD3BC_medium_replay",
     "control_sweep": "data/output/test_v9_batch256/walker2d/td3_bc/data_medrep/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medrep/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medrep/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/td3_bc_online/data_medrep/best", [0]],
     },
    {"label": "TD3BC_medium_expert",
     "control_sweep": "data/output/test_v9_batch256/walker2d/td3_bc/data_medexp/sweep",
     "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medexp/sweep", [0]],
     # "control": ["data/output/test_v9_batch256/walker2d/td3_bc/data_medexp/best", [0]],
     "fine_tune": ["data/output/test_v9_batch256/walker2d/td3_bc_online/data_medexp/best", [0]],
     },
]

